apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: "Cleans up the workspace by deleting all files and directories"
  workspaces:
    - name: source
      description: The workspace that we want to clean up
  steps:
    - name: cleanup
      image: alpine:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning up workspace at $(pwd)"
        rm -rf *
        echo "Workspace cleaned up"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  description: "Runs tests using nose test framework"
  workspaces:
    - name: source
      description: The workspace containing the source code
  params:
    - name: nose-options
      type: string
      description: Additional options for nose
      default: "--with-coverage --cover-package=service --verbose"
  steps:
    - name: install-dependencies
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing dependencies..."
        pip install nose coverage
        pip install -r requirements.txt

    - name: run-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running nose tests with options: $(params.nose-options)"
        nosetests $(params.nose-options)
